name: Docs CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v4

      # Validate Markdown
      # - name: Lint Markdown
      #   uses: actionshub/markdownlint@main

      # Install dependencies
      - name: Install tools
        run: |
          sudo apt-get install pandoc -y
          npm install -g @marp-team/marp-cli

      # Process single files
      - name: Convert individual files
        run: |
          # Create output directory
          mkdir -p outputs
           # Copy images to a temporary directory (prevents path issues)
          mkdir -p temp_images
          find docs -name "*.jpg" -exec cp {} temp_images/ \;
          
          # Convert individual MD files to DOCX
          if [ -d "docs/one_file" ] && [ "$(ls -A docs/one_file/*.md 2>/dev/null)" ]; then
            echo "Converting Markdown files in docs/one_file/"
            
            # Convert each MD file to DOCX
            for file in docs/one_file/*.md; do
              [ -f "$file" ] || continue  # Skip if not a regular file
              output_name="outputs/$(basename "$file" .md).docx"
              echo "Converting $file to $output_name"
              pandoc "$file" -f markdown -t docx -o "$output_name" --resource-path=.:temp_images --extract-media=temp_images
            done
          else
            echo "No Markdown files found in docs/one_file/"
          fi
          
          # Convert README to PDF
          # pandoc docs/README.md -o outputs/README.pdf

      # Combine multiple files
      - name: Merge Markdown to single DOCX
        run: |
          pandoc docs/sep_files/*.md -f markdown -t docx -o outputs/combined.docx \
            --toc \
            --resource-path=.:temp_images \
            --extract-media=temp_images
            --metadata-file=docs/meta.yaml || echo "No files to combine"

      # Process presentations
      - name: Generate presentations
        run: |
          mkdir -p outputs/presentations
          for file in $(find slides -name "*_presentation.md"); do
            output_name="outputs/presentations/$(basename "$file" .md).pptx"
            marp "$file" --pptx --output "$output_name"
          done || echo "No presentations found"

      # Upload all artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: documentation-exports
          path: |
            outputs/*.docx
            outputs/*.pdf
            outputs/presentations/*.pptx