name: Release Documentation

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags (e.g., v1.0.0)

permissions:
  contents: write  # Required for creating releases

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install tools
      - name: Install dependencies
        run: |
          sudo apt-get install pandoc -y
          npm install -g @marp-team/marp-cli

      # Convert documents
      - name: Generate documents
        run: |
          mkdir -p outputs
          
          # Convert individual files
          if [ -d "docs/one_file" ]; then
            for file in docs/one_file/*.md; do
              [ -f "$file" ] || continue
              output_name="outputs/$(basename "$file" .md).docx"
              pandoc "$file" -f markdown -t docx -o "$output_name" \
                --resource-path=.:docs/one_file:dist \
                --extract-media=dist 
            done
          fi

          # Create combined document
          if ls docs/sep_files/*.md 1> /dev/null 2>&1; then
            pandoc docs/sep_files/*.md -o outputs/combined.docx \
              --toc \
              --resource-path=.:docs/sep_files:dist \
              --extract-media=dist \
              --metadata-file=docs/meta.yaml
          fi

      # Create release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
            files: |
                outputs/*.docx
                outputs/presentations/*.pptx
            tag_name: ${{ github.ref_name }}
            name: "Version ${{ github.ref_name }}"
            body: |
                Documentation for ${{ github.ref_name }}
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}